[project]
name = "drippet-python"
version = "1.0.0"
dependencies = [
    "beaupy==3.12.0",
    "bleak==3.0.1",
    "crc==7.1.0",
    "emoji==2.15.0",
    "rich==15.0.0",
    "pyserial==3.5",
]

[tool.setuptools]
py-modules = ["constants"]

[tool.setuptools.packages.find]
include = ["ble*", "transport*"]

[project.scripts]
ssay = "ble.discover:do_it"
